import ctypes
from typing import Any
from models import CanonicalEvent, QualityConfig

HAS_FASTPATH: bool

class FastQualityEngine:
    is_native: bool
    thread_safe: bool
    cfg: QualityConfig
    counts: dict[str, int]
    reason_counts: dict[str, int]

    def __init__(self, cfg: QualityConfig | None = None, thread_safe: bool = False) -> None: ...
    def evaluate(self, event: CanonicalEvent) -> CanonicalEvent: ...
    def evaluate_batch(self, events: list[CanonicalEvent]) -> list[CanonicalEvent]: ...
    def reset(self) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> FastQualityEngine: ...
    def __exit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...
